version: '3.8'

services:
  server:
    build: .
    ports:
      - '3050:3050'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - DB_DATABASE=testdb
      - JWT_SECRET=finalTeamMainYuna
      - JWT_EXPIRES_IN=3600s
      - JWT_REFRESH_SECRET=finalTeamMainJunYongRefresh
      - JWT_REFRESH_EXPIRES_IN=30d
      - AWS_REGION=ap-northeast-2
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
